global:
  scrape_interval: 15s
  
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

scrape_configs:
  - job_name: 'spark-train-2'
    static_configs:
      - targets: ['spark-train-2:4040']
